[versions]
agp = "8.13.0"
kotlin = "2.2.21"
compose-bom = "2025.10.01"
core-ktx = "1.17.0"
ksp = "2.3.0"
activity-compose = "1.11.0"
lifecycle = "2.9.4"
okio = "3.16.2"
hilt = "1.3.0"
dagger = "2.57.2"
okhttp = "5.3.0"
navigation = "2.9.5"
serialization = "1.9.0"
documentfile = "1.1.0"
shizuku = "13.1.5"
libsu = "6.0.0"
datastore = "1.1.7"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku"}
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku"}

libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }